import React, {ReactElement, useEffect, useState} from "react";
import NavBar from "../navBar/NavBar";
import {ThemeContext, useThemeContext} from "../../contexts/ThemeContext";
import styles from "./BasicLayout.module.css";
import Head from "next/head";
import {background} from "./styles";

interface Props {
    children: ReactElement;
}

const BasicLayout: React.FunctionComponent<Props> = (props: Props) => {

    const [dark, setDark] = useState(true);

    //detect if user prefers dark mode
    /*
        useEffect(() =>
            setDark(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches)
        ,[]
    )
     */

    return (
        <ThemeContext.Provider value={{dark,setDark}}>
            <div className={`flex container ${styles.container}`}>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <NavBar/>
                <main className={`${styles.main}`}>
                    {props.children}
                </main>
                <style>{background(dark)}</style>
            </div>
        </ThemeContext.Provider>
    )
}

export default BasicLayout